Repository owncloud/testing, pull requests merged in 2018-10, with the labels that each got.

#32 Correctly parse occ commands that have quoted strings containing spaces
  lib/Occ.php
Labels: 3 - To Review, QA-team

#27 Bugfix/25 - use insertIfNotExist
  .drone.yml
  .gitignore
  Makefile
  appinfo/routes.php
  lib/BigFileID.php
  phpunit.xml
  tests/bootstrap.php
  tests/unit/lib/BigFileIDTest.php
Labels: 4 - To Release

#33 Allow quoted strings in occ commands
  lib/Occ.php
Labels: 3 - To Review, QA-team

#34 Allow quoted strings like --display-name='User One'
  lib/Occ.php
Labels: 3 - To Review, QA-team

#38 Setup acceptance test for testing app
  .drone.yml
  Makefile
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiTestingApp/testing.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
Labels: 3 - To Review, QA-team

#39 Add textfile0.txt to webUI skeleton
  data/webUISkeleton/textfile0.txt
Labels: 3 - To Review, QA-team

#40 Add config for running on different php versions and branch on drone
  .drone.yml
Labels: 3 - To Review, QA-team

#41 Add test for checking logfile line numbers in api
  tests/acceptance/features/apiTestingApp/testing.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 3 - To Review, QA-team

#43 Add api acceptance tests for checking adding and deleting config keys
  tests/acceptance/features/apiTestingApp/testing.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 3 - To Review, QA-team

#44 Add api acceptance tests for adding and deleting multiple config keys
  tests/acceptance/features/apiTestingApp/testing.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 3 - To Review, QA-team

#45 Added test for checking App info returned in the response
  tests/acceptance/features/apiTestingApp/testing.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 3 - To Review, QA-team

#48 Allow to operate on owncloud 11
  appinfo/info.xml
Labels: 3 - To Review

#49 Fix some more phpstan errors
  lib/Dav/SlowdownPlugin.php
Labels: 3 - To Review

#51 show owncloud logs in drone
  .drone.yml
Labels: 3 - To Review, QA-team

#53 Bump max-version to 11.0.0.0
  appinfo/info.xml
Labels: 3 - To Review, QA-team

#54 API acceptance tests for serverfiles
  appinfo/routes.php
  lib/ServerFiles.php
  tests/acceptance/features/apiTestingApp/serverFiles.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 3 - To Review, QA-team

#55 Refactor tests for creating and deleting serverfiles
  tests/acceptance/features/apiTestingApp/serverFiles.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 3 - To Review, QA-team

#56 Add test for create and delete directory in server root
  lib/ServerFiles.php
  tests/acceptance/features/apiTestingApp/serverFiles.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 3 - To Review, QA-team

#57 Return urlEncoded response content
  lib/ServerFiles.php
Labels: 3 - To Review, QA-team

#58 Add API acceptance test for creating and deleting notifications
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiTestingApp/notifications.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 3 - To Review, QA-team

#59 Add test to check max file id feature
  tests/acceptance/features/apiTestingApp/testing.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 3 - To Review, QA-team

#60 Add API accpeptance test for checking clear logfile
  tests/acceptance/features/apiTestingApp/testing.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 4 - To Release, QA-team

#62 Testing app supports any 11.0.0.*
  appinfo/info.xml
Labels: 3 - To Review, QA-team
