Repository owncloud/testing, pull requests merged in 2018-11, with the labels that each got.

#63 failOnWarning="true"
  phpunit.xml
Labels: 3 - To Review

#65 Remove redundant steps from testing app
  tests/acceptance/features/apiTestingApp/testing.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 3 - To Review, QA-team

#68 Refactor changed core test steps
  tests/acceptance/features/apiTestingApp/notifications.feature
  tests/acceptance/features/apiTestingApp/testing.feature
Labels: 3 - To Review, QA-team

#69 add --remote for running acceptance tests
  Makefile
Labels: 4 - To Release, QA-team

#70 Adjust acceptance test steps like changed in core
  tests/acceptance/features/apiTestingApp/notifications.feature
  tests/acceptance/features/apiTestingApp/serverFiles.feature
  tests/acceptance/features/apiTestingApp/testing.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 4 - To Release, QA-team, dev:acceptance-tests

#71 Fix logfile.php
  lib/Logfile.php
Labels: 3 - To Review, QA-team

#73 Fix steps changed in core
  tests/acceptance/features/apiTestingApp/notifications.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests
