Repository owncloud/testing, pull requests merged in 2018-12, with the labels that each got.

#74 Implement recent CI-script standards
  .drone.yml
  Makefile
  phpunit.xml
  vendor-bin/php-parallel-lint/composer.json
Labels: 4 - To Release, QA-team

#76 More flexible Makefile help column format
  Makefile
Labels: 4 - To Release, QA-team

#77 Add build status badge
  README.md
Labels: 4 - To Release, QA-team

#78 use bootstrap.php of core acceptance tests
  tests/acceptance/features/bootstrap/bootstrap.php
Labels: 4 - To Release, QA-team, dev:acceptance-tests

#75 Implement phan stan
  .drone.yml
  .gitignore
  .phan/config.php
  Makefile
  appinfo/routes.php
  lib/Config.php
  lib/Dav/SlowdownPlugin.php
  lib/Locking/FakeDBLockingprovider.php
  lib/Locking/Provisioning.php
  lib/Logfile.php
  lib/Notifications.php
  phpstan.neon
  vendor-bin/phan/composer.json
  vendor-bin/phpstan/composer.json
Labels: 3 - To Review, QA-team

#80 Implement phpstan
  .drone.yml
  lib/Locking/FakeDBLockingProvider.php
  lib/ServerFiles.php
Labels: 3 - To Review, QA-team

#79 Add endpoint for getExtension from MimeType
  appinfo/routes.php
  lib/Config.php
  tests/acceptance/features/apiTestingApp/testing.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests
