Repository owncloud/testing, pull requests merged in 2018-09, with the labels that each got.

#12 Support passing env variables with occ commands
  lib/Occ.php
Labels: QA-team

#11 Add endpoints sysinfo, dir and file
  appinfo/routes.php
  lib/ServerFiles.php
  lib/SysInfo.php
Labels: QA-team

#16 combine server environment vars with explicitly set vars
  lib/Occ.php
Labels: QA-team

#20 Code style
  lib/Occ.php
Labels: 3 - To Review, QA-team

#22 implement ownCloud coding standard
  .drone.yml
  .gitignore
  .php_cs.dist
  Makefile
  vendor-bin/owncloud-codestyle/composer.json
Labels: 3 - To Review

#24 Remote OCC env vars
  lib/Occ.php
Labels: 3 - To Review

#21 allow to slowdown dav requests
  appinfo/info.xml
  appinfo/routes.php
  lib/Dav/SlowdownPlugin.php
  lib/DavSlowdown.php
Labels: 3 - To Review, QA-team

#23 Fix testing app for oracle
  lib/Application.php
Labels: 3 - To Review

#30 Implement routes for getting config values of an app
  appinfo/routes.php
  lib/Config.php
Labels: 3 - To Review, QA-team

#29 Add capability to delete files and folders
  appinfo/routes.php
  lib/ServerFiles.php
Labels: 3 - To Review, QA-team
