Repository owncloud/testing, pull requests merged in 2019-02, with the labels that each got.

#85 Add testing command to create and login multiple users for testing large instances
  Makefile
  appinfo/info.xml
  lib/Command/CreateMultiUser.php
Labels: 4 - To Release

#87 Delete build and vendor when doing make clean
  Makefile
Labels: 4 - To Release, QA-team

#88 new endpoint to work with skeletondirectories used for testing
  Makefile
  appinfo/routes.php
  lib/TestingSkeletonDirectory.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#90 do not trim content of downloaded file
  lib/ServerFiles.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#91 delete skeletondirectory setting before setting it
  lib/TestingSkeletonDirectory.php
Labels: 4 - To Release, QA-team, dev:acceptance-tests
