Repository owncloud/testing, pull requests merged in 2019-04, with the labels that each got.

#94 allow to read a file by absolute path
  lib/ServerFiles.php
Labels: 4 - To Release, QA-team, dev:acceptance-tests

#95 Phpunit 5 6
  composer.lock
  phpunit.xml
  tests/acceptance/features/bootstrap/TestingAppContext.php
  tests/unit/lib/BigFileIDTest.php
Labels: 4 - To Release, QA-team

#52 Test for Lock Provisoning using testing app
  tests/acceptance/features/apiTestingApp/lockProvisioning.feature
  tests/acceptance/features/bootstrap/TestingAppContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#96 Add notify step to drone
  .drone.yml
Labels: 3 - To Review
