Repository owncloud/testing, pull requests merged in 2020-03, with the labels that each got.

#137 Pin behat/mink to 1.7.1 and update other acceptance test dependencies
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#139 [Tests-Only] API register to list file in directory
  appinfo/routes.php
  lib/ServerFiles.php
Labels: 3 - To Review, QA-team

#140 [Tests-Only] Removing preg_rep from method listFiles
  lib/ServerFiles.php
Labels: 4 - To Release, QA-team
